### ISSUE TITLE
Caching or Seeding isn't working for direct datahorse installations

### ISSUE THREAD

**Issue by Sohammhatre10** [DeDolphins/DataHorse#18]
Hello @SsebowaDisan ,

The seeding, caching issues related to #9 do not work for direct datahorse import even if it being updated on Git, will you check it.

<img width="559" alt="image" src="https://github.com/user-attachments/assets/09610b3f-4b8e-456b-8c45-fc730f911df4">

This is the link for the notebook
https://colab.research.google.com/drive/1Hi3NJjNhJ-IXCP7LB5PDXiJCAH_drBXW#scrollTo=NLTA7eW_a954

**Comment by SsebowaDisan** [comment]
Hello @Sohammhatre10 , 
Thanks for addressing the issue.
I am looking into this.

**Comment by SsebowaDisan** [comment]
Hello @Sohammhatre10,
This issue is solved.
![image](https://github.com/user-attachments/assets/5bf78fa6-405f-4d80-812f-1504d147ec2f)
