### ISSUE TITLE
Hilarious documentation bug in dataset description

### ISSUE THREAD

**Issue by sanjaydasgupta** [DeDolphins/DataHorse#21]
The [Examples](https://github.com/DeDolphins/DataHorse#examples) section of [README.md](https://github.com/DeDolphins/DataHorse/blob/main/README.md) says: "We’re using an **Irish dataset** as an example".

That line should read "We’re using the [Iris flower dataset](https://en.wikipedia.org/wiki/Iris_flower_data_set) as an example" instead.

**Comment by SsebowaDisan** [comment]
Thanks @sanjaydasgupta, for letting us and correcting it. Appreciated!
